### ISSUE TITLE
Link to "Securing Workloads in the IBM Cloud" points to an unrelated site.

### ISSUE THREAD

**Issue by floresam** [IBM-Bluemix-Docs/overview#13]
The link at the end of this page points users to https://www.ibm.com/cloud/learn/iaas-paas-saas which provides an overview of various cloud computing models, not on securing workloads. The sentence that link ends implies that the link will provide security details specific to the PaaS portion of IBM Cloud. Do we have a specific PaaS securing workloads page to link users to? Clients ask for this often so it may be a good idea to create one if we don't have it. Happy to help if need be.

**Comment by mekaufman** [comment]
@floresam Thank you for the feedback. I have updated the content surrounding the link to make it clear that the link leads to general information about securing apps and the customer's environment as the short term fix.

We do not have a page specific to securing PaaS workloads that I know of. Most of the security content has moved out to the ibm.com/garage site https://www.ibm.com/cloud/garage/architectures/securityArchitecture/overview and the Cloud docs team does not author that content. If clients are asking for this information through channels that go through you, maybe you can help to author some content out on the garage method site? I'm going to see if I can get a contact, and then I can email you more details.
