### ISSUE TITLE
Where is the category for Network?

### ISSUE THREAD

**Issue by llundquist** [IBM-Bluemix-Docs/overview#14]
I think there ought to be a category for Network features and services, similar to Compute. They are separate areas. I think this paragraph would be a good place to start:

Stay up-to-date with the new features and services that are available in {{site.data.keyword.Bluemix}}, so that you get the most out of your {{site.data.keyword.Bluemix_notm}} experience. The updates are organized into these categories: {{site.data.keyword.Bluemix_notm}} platform, {{site.data.keyword.Bluemix_local_notm}} and {{site.data.keyword.Bluemix_dedicated_notm}}, Compute, **ADD NETWORK HERE**, and Services. {:shortdesc}

**Comment by llundquist** [comment]
For instance, we will have vSRX Juniper available soon as an option for network security for customers.

**Comment by mekaufman** [comment]
@llundquist Are these network services that are being reported or something separate that would necessitate the need for a new category?

**Comment by llundquist** [comment]
I believe it needs a new category on the page, on par with "Compute"

BTW, Since I posted this issue, Lili and I did have one conversation with Jenifer, and I believe she is in agreement and understands the issue, if that is helpful to you

**Comment by jenschlot** [comment]
For the "What's New" page...I don't want to manually maintain service "categories", especially since they just changed in the catalog. There is a separate effort to see if we can enhance the "What's New" to be a landing page where we can do things like filter and perhaps pull in these snippets into the console.

For now, let's just include the "service" name in alphabetical order, by date...

**Comment by llundquist** [comment]
I don't think What's New is quite the page we had been discussing before--I am going to try to find a link to post here. I think it is what used to be called the catalog page, which has been changed recently.

**Comment by llundquist** [comment]
No, it was not that page--this is the page it is NOT: https://console.bluemix.net/catalog/

Was there some type of new version of a catalog page?

**Comment by llundquist** [comment]
Essentially, I would like Network to be handled in the same way as Compute.

**Comment by llundquist** [comment]
Here is the page: https://console.bluemix.net/docs/

**Comment by jenschlot** [comment]
Closing. We have another issue we're using to track.

**Comment by llundquist** [comment]
@jenschlot Could you please provide the link to the other issue you are using to track this item? Thank you! I am very interested to follow it and I am also being asked by my management to follow it.

**Comment by llundquist** [comment]
@jenschlot Is there an update on this topic? If you sent it, I never received the link to the other issue you're using to track this item. @cdmauney can you fill me in, possibly?
