### ISSUE TITLE
Cloud Integration section seriously out of date 

### ISSUE THREAD

**Issue by rodalton** [IBM-Bluemix-Docs/overview#16]
The section titled 'Cloud Integration API' should be removed/re-written. 

Per the linked page _On July 14, 2016, the Cloud Integration service tile was removed from the Bluemix® catalog and you are no longer able to provision new instances._

**Comment by mekaufman** [comment]
This content is currently being rewritten

**Comment by mekaufman** [comment]
In the current draft, I've commented out the sections referring to Cloud Integration API, so the outdated content isn't available as we rewrite it.
