### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by bwentwor** [IBM-Bluemix-Docs/overview#19]
Please check the links on the following page. Most of the links on the top half of the page are broken.
https://console.bluemix.net/docs/overview/terms-of-use/notices.html#terms

**Comment by bwentwor** [comment]
@mlgordon @cdmauney @neal-timpe Please take a look at this defect.

**Comment by cdmauney** [comment]
@bwentwor All of the links work for me.

**Comment by mekaufman** [comment]
@cdmauney If they work, can we close this?

**Comment by cdmauney** [comment]
Yep, closing.

**Comment by bwentwor** [comment]
Sorry...this issue got into my personal email spam. The day I opened the issue, all of the links were broken. They seem to be working today. It must have been a server issue.
