### ISSUE TITLE
API Endpoint for Dallas

### ISSUE THREAD

**Issue by bijoalex** [IBM-Bluemix-Docs/overview#22]
Below page mentions "api.us-south.bluemix.net" as API endpoint for Dallas. However, this endpoint does not appear to work. Instead it's api.ng.bluemix.net that's working with "ibmcloud api".

https://console.bluemix.net/docs/overview/ha-regions.html#ov_intro_reg

**Comment by neal-timpe** [comment]
Making that fix in production now.
