### ISSUE TITLE
Email Link for Sales Team Bounces

### ISSUE THREAD

**Issue by cmdx** [IBM-Bluemix-Docs/overview#27]
In the HIPAA section the last sentence says:

**There can be issues arising from the merging of IBM Cloud Public with classic infrastructure. For more information or assistance to achieve, certify, and maintain HIPAA compliance for your IBM Cloud environment, contact the IBM Cloud sales team.**

The email link: cloudplatform_compliance@us.ibm.com here bounces.  Where do we get HIPAA help?

**Comment by cdmauney** [comment]
Emailed Carol O'Neill on Dec 17 to confirm where we should point users to. Will send a follow-up today.

**Comment by mekaufman** [comment]
@cdmauney Any update from Carol?

**Comment by cdmauney** [comment]
@mekaufman Just sent another follow-up to the contacts that Carol pointed me to.

**Comment by cdmauney** [comment]
We've pulled this section from the doc, and we're pointing to the IBM Cloud compliance page instead. This page provides a web form for clients to contact IBM to request the list of all other IBM Cloud HIPAA-ready services other than IaaS: https://www.ibm.com/account/reg/us-en/signup?formid=MAIL-wcp.
