### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pizzamax** [IBM-Bluemix-Docs/overview#32]
In "overview/it-ops-journey.md", there is a broken link in the following section.

Networking
{: #network}

You automatically get connectivity to the {{site.data.keyword.vpn_full}} when your {{site.data.keyword.cloud_notm}} account is set up. By default, your server has a public IP address and a private IP address. If you want your server to be private, you can either turn off the public interface after your server is provisioned or order your server as private. See Getting started with Virtual Private Networking for more information.

The link to **_Getting started with Virtual Private Networking_** is broken.

**Comment by cdmauney** [comment]
Link is fixed.
