### ISSUE TITLE
Government safity us to Join D 

### ISSUE THREAD

**Issue by Dhivyanshup** [IBM-Bluemix-Docs/overview#36]
![1548521095091](https://user-images.githubusercontent.com/45223414/57565588-290a8500-73de-11e9-954d-fecbff9391c6.jpg)
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by cdmauney** [comment]
@Dhivyanshup Can you provide details about the item that prompted you to open this issue?
